import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const pkgPath = join(__dirname, '..', 'package.json');
const outDir = join(__dirname, '..', 'lib');

try {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
  const version = pkg.version || '0.0.0';

  const content = `/**
 * This file is auto-generated by scripts/generate-version.mjs
 * Do not edit manually.
 */
export const VERSION = '${version}';
`;

  const outPath = join(outDir, 'version.ts');
  writeFileSync(outPath, content, 'utf-8');
  console.log(`✓ Generated ${outPath} with version ${version}`);
} catch (error) {
  console.error('Failed to generate version file:', error);
  process.exit(1);
}
